<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>管理员后台</title>
    <include file="./Application/Canmou/View/before_body.phtml"/>
</head>
<body class="no-skin">

<include file="./Application/Canmou/View/navbar.phtml"/>
<div class="main-container" id="main-container">
    <include file="./Application/Canmou/View/sidebar.phtml"/>
    <!--begin-->
    <div class="main-content">
        <div class="page-content">
            <div class="page-content-area">
                <div class="page-header">
                    <b><h1>
                            <if condition="isset($ad)">
                                编辑广告
                                <else/>
                                添加广告
                            </if>
                        </h1></b>
                </div>
                <include file="./Application/Canmou/View/tip.phtml"/>
                <div class="row">
                    <div class="col-xs-12">
                        <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data">
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-right" for="form-field-1">广告名称</label>
                                <div class="col-sm-8">
                                    <input type="text" id="form-field-1" class="col-xs-10 col-sm-6" name="name" value="{$ad.name}"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-left" for="form-field-1">广告描述
                                </label>
                                <div class="col-sm-8">
                                    <input type="text" id="form-field-1" class="col-xs-10 col-sm-6" name="desc" value="{$ad.desc}"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-left" for="form-field-1">图片
                                </label>
                                <div class="col-sm-8">
                                    <if condition="$ad">
                                        <img src="{$ad.img}" width="190px" height="120px">
                                    </if>
                                    <input type="file" name="image_path" accept="image/*">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-left" for="form-field-1">目标链接地址
                                </label>
                                <div class="col-sm-8">
                                    <input type="text" id="form-field-1" class="col-xs-10 col-sm-6" name="url" value="{$ad.url}"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-left" for="form-field-1">类型
                                </label>
                                <div class="col-sm-8">
                                    <input type="text" id="form-field-1" class="col-xs-10 col-sm-6" name="type" value="{$ad.type}"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 no-padding-right control-label">状态</label>
                                <div class="radio">
                                    <if condition="$ad.status eq '0'">
                                        <label>
                                            <input type="radio" name="status" class="ace"  value="1"/>
                                            <span class="lbl">启用</span>
                                        </label>
                                        <label>
                                            <input type="radio" name="status" checked="checked" class="ace" value="0"/>
                                            <span class="lbl">禁用</span>
                                        </label>
                                        <else/>
                                        <label>
                                            <input type="radio" name="status" class="ace" checked="checked" value="1"/>
                                            <span class="lbl">启用</span>
                                        </label>
                                        <label>
                                            <input type="radio" name="status" class="ace"  value="0"/>
                                            <span class="lbl">禁用</span>
                                        </label>
                                    </if>
                                </div>
                            </div>
                            <div class="clearfix form-actions">
                                <div class="col-md-offset-3 col-md-9">
                                    <button class="btn btn-info" type="submit">提交</button> &nbsp; &nbsp; &nbsp;
                                    <a href="/canmou/cate/index">
                                        <button class="btn" type="button">返回</button>
                                    </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!--end-->
    <div class="footer">
        <div class="footer-inner">
            <div class="footer-content">
						<span class="bigger-120">
							Application &copy; 2013-2014
						</span>
            </div>
        </div>
    </div>
</div>
<include file="./Application/Canmou/View/after_body.phtml"/>
</body>
</html>