<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>管理员后台</title>
    <include file="./Application/Canmou/View/before_body.phtml"/>
    <link rel="stylesheet" href="__PUBLIC__css/nestable.css"/>
</head>
<body class="no-skin">

<include file="./Application/Canmou/View/navbar.phtml"/>
<div class="main-container" id="main-container">
    <include file="./Application/Canmou/View/sidebar.phtml"/>
    <!--begin-->

    <div class="main-content">
        <div class="page-content">
            <div class="page-content-area">
                <div class="page-header">
                    <h1>类目列表</h1>'
                    <include file="./Application/Canmou/View/tip.phtml"/>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="dd" id="nestable">
                                    <ol class="dd-list">
                                        <foreach name="cateList" item="cate">
                                        <li class="dd-item" data-id="{$cate.cid}">
                                            <div class="dd-handle">
                                                {$cate.name}
                                                <div class="pull-right action-buttons">
                                                    <a class="blue" href="/canmou/cate/edit?id={$cate.cid}">
                                                        <i class="ace-icon fa fa-pencil bigger-130"></i>
                                                    </a>
                                                    <a class="red" href="/canmou/cate/delete?id={$cate.cid}">
                                                        <i class="ace-icon fa fa-trash-o bigger-130"></i>
                                                    </a>
                                                </div>
                                            </div>
                                            <if condition="$cate.children neq null">
                                            <ol class="dd-list">
                                                <foreach name="cate.children" item="va">
                                                <li class="dd-item item-blue2" data-id="{$va.cid}">
                                                    <div class="dd-handle">{$va.name}
                                                        <div class="pull-right action-buttons">
                                                            <a class="blue" href="/canmou/cate/edit?id={$va.cid}">
                                                                <i class="ace-icon fa fa-pencil bigger-130"></i>
                                                            </a>
                                                            <a class="red" href="/canmou/cate/delete?id={$va.cid}">
                                                                <i class="ace-icon fa fa-trash-o bigger-130"></i>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </li>
                                                </foreach>
                                            </ol>
                                            </if>
                                        </li>
                                        </foreach>
                                    </ol>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--end-->
    <div class="footer">
        <div class="footer-inner">
            <div class="footer-content">
						<span class="bigger-120">
							Application &copy; 2013-2014
						</span>
            </div>
        </div>
    </div>
</div>
<include file="./Application/Canmou/View/after_body.phtml"/>
<script src="__PUBLIC__js/jquery.nestable.min.js"></script>
<script type="text/javascript">
    jQuery(function($){
        $('#nestable').nestable({
            group: 1,
            maxDepth: 2
        }).on("change", function() {
            $.post('/canmou/cate/ajaxorder', {
                list: JSON.stringify($('#nestable').nestable('serialize'))
            }, function(data) {
                if (data){
                    alert('类目更新成功');
                }else{
                    alert('类目更新失败');
                };
            }, 'json');
        });
        $('.dd-handle a').on('mousedown', function(e){
            e.stopPropagation();
        });
    });
</script>
</body>
</html>
