<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta charset="utf-8" />
		<title>管理员后台</title>
        <include file="./Application/Canmou/View/before_body.phtml"/>
	</head>
	<body class="no-skin">
    <include file="./Application/Canmou/View/navbar.phtml"/>

		<div class="main-container" id="main-container">
            <include file="./Application/Canmou/View/sidebar.phtml"/>
<!--begin-->
<div class="main-content"> 
   	<div class="page-content"> 
    	<div class="page-content-area">
    		<div class="row">
    			<div class="col-xs-12">
				    <div class="col-sm-9 infobox-container">
						<div class="infobox infobox-green">
							<div class="infobox-icon">
								<i class="ace-icon fa fa-comments"></i>
							</div>
							<div class="infobox-data">
								<span class="infobox-data-number">{$pronum|default="0"}</span>
								<div class="infobox-content">产品总数量</div>
							</div>
						</div>
						<div class="infobox infobox-blue">
							<div class="infobox-icon">
								<i class="ace-icon fa fa-user"></i>
							</div>
							<div class="infobox-data">
								<span class="infobox-data-number">{$adminnum|default="0"}</span>
								<div class="infobox-content">后台用户总数量</div>
							</div>
						</div>
                        <div class="infobox infobox-red">
                            <div class="infobox-icon">
                                <i class="ace-icon fa fa-user"></i>
                            </div>
                            <div class="infobox-data">
                                <span class="infobox-data-number">{$usernum|default="0"}</span>
                                <div class="infobox-content">用户总数</div>
                            </div>
                        </div>
                        <div class="infobox infobox-orange">
                            <div class="infobox-icon">
                                <i class="ace-icon fa fa-user"></i>
                            </div>
                            <div class="infobox-data">
                                <span class="infobox-data-number">{$shopnum|default="0"}</span>
                                <div class="infobox-content">店铺总数</div>
                            </div>
                        </div>
                        <div class="infobox infobox-pink">
                            <div class="infobox-icon">
                                <i class="ace-icon fa fa-shopping-cart"></i>
                            </div>
                            <div class="infobox-data">
                                <span class="infobox-data-number">{$shopnum|default="0"}</span>
                                <div class="infobox-content">订单总数</div>
                            </div>
                        </div>
				    </div>
			    </div>
			</div>
    	</div>
    </div>
</div>
<!--end-->
			<div class="footer">
				<div class="footer-inner">
					<div class="footer-content">
						<span class="bigger-120">
							Application &copy; 2013-2014
						</span>
					</div>
				</div>
			</div>
		</div>
    <include file="./Application/Canmou/View/after_body.phtml"/>
</body>
</html>
