<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta charset="utf-8" />
		<title>管理员后台</title>
{include file='../view/before_body.phtml'}
	</head>
	<body class="no-skin">
		
{include file='../view/navbar.phtml'}
		<div class="main-container" id="main-container">
{include file='../view/sidebar.phtml'}
<!--begin-->

<div class="main-content">
	<div class="page-content">
		<div class="page-content-area">
			<div class="row">
				<div class="col-xs-12">
					{if isset($tip) && $tip}
					{include file=$tip}
					{/if}
					<h3 class="header smaller lighter blue">信息列表</h3>
					<div>
						<div id="sample-table-2_wrapper" class="dataTables_wrapper form-inline no-footer">
							<div class="row">
								<div class="col-xs-6">
								   	<div class="dataTables_length" id="sample-table-2_length">
								    	<label>分类
								    		<select name="sample-table-2_length" aria-controls="sample-table-2" class="form-control input-sm">
									    		<option value="10">选择分类</option>
									    		<option value="25">25</option>
								    		</select> 
								    	</label>
								   	</div>
								 </div>
								<div class="col-xs-6">
									<div id="sample-table-2_filter" class="dataTables_filter">
										<label>信息搜索<input type="search" class="form-control input-sm" aria-controls="sample-table-2"></label>
									</div>
								</div>
							</div>
							<table id="sample-table-2" class="table table-striped table-bordered table-hover dataTable no-footer">
								<thead>
									<tr role="row">
										<th width="60px" class="center sorting_disabled">
											<label class="position-relative">
												<input type="checkbox" class="ace">
												<span class="lbl"></span>
											</label>
										</th>
										<th>标题</th>
										<th>发布人</th>
										<th width="180px">时间</th>
										<th width="100px">状态</th>
										<th width="70px">操作</th>
									</tr>
								</thead>

								<tbody>
									<tr role="row" class="even">
										<td class="center">
											<label class="position-relative">
												<input type="checkbox" class="ace">
												<span class="lbl"></span>
											</label>
										</td>

										<td></td>
										<td>$55</td>
										<td>Feb 24</td>

										<td class="hidden-480 sorting_1">
											<span class="label label-sm label-success"></span>
										</td>

										<td>
											<div class="hidden-sm hidden-xs action-buttons">
												<a class="green" href="#" >
													<i class="ace-icon fa fa-pencil bigger-130"></i>
												</a>
											</div>
										</td>
									</tr>
								</tbody>
							</table>
							<div class="row">
							   	<div class="col-xs-6">
							    	
							   	</div>
							   	<div class="col-xs-6">
								   	<div class="dataTables_paginate paging_simple_numbers" id="sample-table-2_paginate">
								   	{html_pagination page="1" rows="2" count="4" url="../admin"|cat:'?page=%page%'}
								   	</div>
							   	</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!--end-->
			<div class="footer">
				<div class="footer-inner">
					<div class="footer-content">
						<span class="bigger-120">
							Application &copy; 2013-2014
						</span>
					</div>
				</div>
			</div>
		</div>
{include file='../view/after_body.phtml'}
</body>
</html>
