{include file='../view/before_body.phtml'}
	</head>
	<body class="no-skin">
		
{include file='../view/navbar.phtml'}
		<div class="main-container" id="main-container">
{include file='../view/sidebar.phtml'}
<!--begin-->

{include file='../view/'|cat:$main|cat:'.phtml'}

<!--end-->
			<div class="footer">
				<div class="footer-inner">
					<div class="footer-content">
						<span class="bigger-120">
							Application &copy; 2013-2014
						</span>
					</div>
				</div>
			</div>
		</div>
{include file='../view/after_body.phtml'}
</body>
</html>
