<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>管理员后台</title>
    <include file="./Application/Canmou/View/before_body.phtml"/>
    <link rel="stylesheet" href="__PUBLIC__css/webuploader.css"/>
    <link rel="stylesheet" href="__PUBLIC__css/uploaderstyle.css"/>
    <link rel="stylesheet" href="__PUBLIC__css/dropzone.css"/>
</head>
<body class="no-skin">

<include file="./Application/Canmou/View/navbar.phtml"/>
<div class="main-container" id="main-container">
    <include file="./Application/Canmou/View/sidebar.phtml"/>
    <!--begin-->
    <div class="main-content">
        <div class="page-content">
            <div class="page-content-area">
                <div class="page-header">
                    <b><h1>编辑商品</h1></b>
                </div>
                <include file="./Application/Canmou/View/tip.phtml"/>
                <div class="row">
                    <div class="col-xs-12">
                        <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data">
<!--                            <input type="file" name="image_path" accept="image/*" data-style="fileinput" data-inputsize="medium" />-->
<!--                            <input type="text" name="name" value="头部">-->
<!--                            <div id="wrapper">-->
<!--                                <div id="container">-->
<!--                                    <!--头部，相册选择和格式选择-->-->
<!---->
<!--                                    <div id="uploader">-->
<!--                                        <div class="queueList">-->
<!--                                            <div id="dndArea" class="placeholder">-->
<!--                                                <div id="filePicker"></div>-->
<!--                                                <p>单次最多可选5张</p>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                        <div class="statusBar" style="display:none;">-->
<!--                                            <div class="progress">-->
<!--                                                <span class="text">0%</span>-->
<!--                                                <span class="percentage"></span>-->
<!--                                            </div><div class="info"></div>-->
<!--                                            <div class="btns">-->
<!--                                                <div id="filePicker2"></div><div class="uploadBtn">开始上传</div>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </div>-->


                            <div class="col-md-8">
                                <div class="dropzone"></div>
                                <p class="help-block">
                                    仅限上传图片
                                </p>
                            </div>

                            <div class="clearfix form-actions">
                                <div class="col-md-offset-3 col-md-9">
                                    <button class="btn btn-info submit-all" type="submit">提交</button> &nbsp; &nbsp; &nbsp;
                                    <a href="/canmou/user/index">
                                        <button class="btn" type="button">返回</button>
                                    </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!--end-->
    <div class="footer">
        <div class="footer-inner">
            <div class="footer-content">
						<span class="bigger-120">
							Application &copy; 2013-2014
						</span>
            </div>
        </div>
    </div>
</div>
<include file="./Application/Canmou/View/after_body.phtml"/>
<script src="__PUBLIC__js/webuploader.js"></script>
<script src="__PUBLIC__js/upload.js"></script>
<script src="__PUBLIC__js/dropzone/dropzone.min.js"></script>
<script type="text/javascript">
//    $(".submit-all").click(
//        function(e){
//            $('.uploadBtn').click();
//            alert("aa");
//        }
//    );

    var dDropzone = $('.dropzone');
    try {
        dDropzone.dropzone({
            paramName: "file",
            url: "/canmou/product/fileupload",
            autoProcessQueue: false,
            uploadMultiple: true,
            parallelUploads: 10,
            maxFilesize: 2,
            // maxFiles: 10,
            addRemoveLinks : true,
            acceptedFiles: ".jpeg,.jpg,.png,.gif,.JPEG,.JPG,.PNG,.GIF",
            dictResponseError: '上传文件发生错误',
            dictRemoveFile: '删除',
            dictMaxFilesExceeded: '上传失败，超过上传限制',
            init: function() {
                var myDropzone = this;
                myDropzone.on('addedfile', function(file) {

                });
                myDropzone.on('successmultiple', function(files, response) {
                });
                myDropzone.on('removedfile', function(file) {

                });
                $(".submit-all").click(function(e) {
                    alert(myDropzone.getQueuedFiles().length);
                    if (myDropzone.getQueuedFiles().length) {
                        myDropzone.processQueue();
                    }
                });
            }

        });
    } catch(e) {
        alert('批量上传图片不支持老版本浏览器，请更换浏览器重试');
    }
</script>
</body>
</html>