<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>管理员后台</title>
    <include file="./Application/Canmou/View/before_body.phtml"/>
</head>
<body class="no-skin">

<include file="./Application/Canmou/View/navbar.phtml"/>
<div class="main-container" id="main-container">
    <include file="./Application/Canmou/View/sidebar.phtml"/>
    <!--begin-->

    <div class="main-content">
        <div class="page-content">
            <div class="page-content-area">
                <div class="row">
                    <div class="col-xs-12">
                        <h3 class="header smaller lighter blue">店铺列表</h3>
                        <include file="./Application/Canmou/View/tip.phtml"/>
                        <div>
                            <div id="sample-table-2_wrapper" class="dataTables_wrapper form-inline no-footer">
                                <div class="row">
                                    <div class="col-xs-6">
                                        <a href="/canmou/shop/add">
                                            <button class="btn btn-info">添加店铺</button>
                                        </a>
                                    </div>
                                    <div class="col-xs-6">
                                    </div>
                                </div>
                                <table id="sample-table-2" class="table table-striped table-bordered table-hover dataTable no-footer">
                                    <thead>
                                    <tr role="row">
                                        <th width="60px" class="center sorting_disabled">
                                            <label class="position-relative">
                                                <input type="checkbox" class="ace">
                                                <span class="lbl"></span>
                                            </label>
                                        </th>
                                        <th>店铺名称</th>
                                        <th width="200px">店铺描述</th>
                                        <th width="180px">店铺地址</th>
                                        <th width="180px">添加时间</th>
                                        <th width="80px">状态</th>
                                        <th width="100px">操作</th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    <volist name="shops" id="shop">
                                        <tr role="row" class="even">
                                            <td class="center">
                                                <label class="position-relative">
                                                    <input type="checkbox" class="ace">
                                                    <span class="lbl"></span>
                                                </label>
                                            </td>
                                            <td>{$shop['name']}</td>
                                            <td>{$shop['desc']}</td>
                                            <td>{$shop['address']}</td>
                                            <td>{$shop['created']|date="Y-m-d H:m:s",###}</td>
                                            <td>
                                                <if condition="$shop['status'] eq 1">
                                                    <span class="label label-sm label-info">启用</span>
                                                    <else/>
                                                    <span class="label label-sm label-warning">禁用</span>
                                                </if>
                                            </td>
                                            <td>
                                                <div class="hidden-sm hidden-xs action-buttons">
                                                    <a class="green" href="/canmou/shop/edit?id={$shop['sid']}" >
                                                        <i class="ace-icon fa fa-pencil bigger-130"></i>
                                                    </a>
                                                    <!--delete action-->
                                                    <a class="green" href="/canmou/shop/delete?id={$shop['sid']}" >
                                                        <i class="ace-icon fa fa-trash-o bigger-130"></i>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    </volist>
                                    </tbody>
                                </table>
                                <div class="row">
                                    <div class="col-xs-6">
                                        <div class="dataTables_info" id="sample-table-2_info" role="status" aria-live="polite">
                                            共{$count|default=0}条记录
                                        </div>
                                    </div>
                                    <div class="col-xs-6">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--end-->
    <div class="footer">
        <div class="footer-inner">
            <div class="footer-content">
						<span class="bigger-120">
							Application &copy; 2013-2014
						</span>
            </div>
        </div>
    </div>
</div>
<include file="./Application/Canmou/View/after_body.phtml"/>
</body>
</html>
