<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>管理员后台</title>

    <include file="./Application/Canmou/View/before_body.phtml"/>

</head>
<body class="no-skin">

<include file="./Application/Canmou/View/navbar.phtml"/>
<div class="main-container" id="main-container">
    <include file="./Application/Canmou/View/sidebar.phtml"/>
    <!--begin-->

    <div class="main-content">
        <div class="page-content">
            <div class="page-content-area">
                <div class="page-header">
                    <b><h1>
                            <if condition="$shop">编辑店铺信息
                                <else/>添加店铺
                            </if>
                    </h1></b>
                </div>
                <include file="./Application/Canmou/View/tip.phtml"/>
                <div class="row">
                    <div class="col-xs-12">
                        <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data">
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-right" for="form-field-1">店铺名称</label>
                                <div class="col-sm-10">
                                    <input type="text" id="form-field-1" class="col-xs-10 col-sm-6" name="name" value="{$shop.name}"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-left" for="form-field-1">店铺描述
                                </label>
                                <div class="col-sm-6">
                                <textarea name="desc" rows="3" cols="60">{$shop.desc}</textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-left" for="form-field-1">店铺图片</label>
                                <div class="col-sm-6">
                                    <if condition="$shop">
                                        <img src="{$shop.img_path}" width="80px" height="80px">
                                    </if>
                                    <input type="file" name="shop_img" value="上传图片" accept="image/*" data-style="fileinput" data-inputsize="medium" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-left" for="form-field-1">店铺地址
                                </label>
                                <div class="col-sm-6">
                                    <textarea name="address" rows="3" cols="60">{$shop.address}</textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-left" for="form-field-1">联系电话
                                </label>
                                <div class="col-sm-6">
                                    <input type="text" id="form-field-1" class="col-xs-10 col-sm-6" name="telephone" value="{$shop.telephone}"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-left" for="form-field-1">QQ
                                </label>
                                <div class="col-sm-6">
                                    <input type="text" id="form-field-1" class="col-xs-10 col-sm-6" name="qq" value="{$shop.qq}"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 no-padding-right control-label">状态</label>
                                <div class="radio">
                                    <if condition="$shop.status eq '0'">
                                            <label>
                                                <input type="radio" name="status" class="ace"  value="1"/>
                                                <span class="lbl">启用</span>
                                            </label>
                                            <label>
                                                <input type="radio" name="status" checked="checked" class="ace" value="0"/>
                                                <span class="lbl">禁用</span>
                                            </label>
                                        <else/>
                                        <label>
                                            <input type="radio" name="status" class="ace" checked="checked" value="1"/>
                                            <span class="lbl">启用</span>
                                        </label>
                                        <label>
                                            <input type="radio" name="status" class="ace"  value="0"/>
                                            <span class="lbl">禁用</span>
                                        </label>
                                    </if>
                                </div>
                            </div>
                            <div class="clearfix form-actions">
                                <div class="col-md-offset-3 col-md-9">
                                    <button class="btn btn-info" type="submit">提交</button> &nbsp; &nbsp; &nbsp;
                                    <a href="/canmou/shop/index">
                                        <button class="btn" type="button">返回</button>
                                    </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!--end-->
    <div class="footer">
        <div class="footer-inner">
            <div class="footer-content">
						<span class="bigger-120">
							Application &copy; 2013-2014
						</span>
            </div>
        </div>
    </div>
</div>

<include file="./Application/Canmou/View/after_body.phtml"/>

</body>
</html>