<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>管理员后台</title>
    <include file="./Application/Canmou/View/before_body.phtml"/>
    <link rel="stylesheet" href="__PUBLIC__css/webuploader.css"/>
    <link rel="stylesheet" href="__PUBLIC__css/uploaderstyle.css"/>
</head>
<body class="no-skin">

<include file="./Application/Canmou/View/navbar.phtml"/>
<div class="main-container" id="main-container">
    <include file="./Application/Canmou/View/sidebar.phtml"/>
    <!--begin-->
    <div class="main-content">
        <div class="page-content">
            <div class="page-content-area">
                <div class="page-header">
                    <b><h1>
                            <if condition="$usertype eq 'add'">
                                添加管理员
                                <else/>
                                编辑管理员用户
                            </if>
                        </h1></b>
                </div>
                <include file="./Application/Canmou/View/tip.phtml"/>
                <div class="row">
                    <div class="col-xs-12">
                        <form class="form-horizontal" role="form" method="POST">

                                <div id="wrapper">
                                    <div id="container">
                                        <!--头部，相册选择和格式选择-->

                                        <div id="uploader">
                                            <div class="queueList">
                                                <div id="dndArea" class="placeholder">
                                                    <div id="filePicker"></div>
                                                    <p>或将照片拖到这里，单次最多可选300张</p>
                                                </div>
                                            </div>
                                            <div class="statusBar" style="display:none;">
                                                <div class="progress">
                                                    <span class="text">0%</span>
                                                    <span class="percentage"></span>
                                                </div><div class="info"></div>
                                                <div class="btns">
                                                    <div id="filePicker2"></div><div class="uploadBtn">开始上传</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            <div class="clearfix form-actions">
                                <div class="col-md-offset-3 col-md-9">
                                    <button class="btn btn-info" type="submit">提交</button> &nbsp; &nbsp; &nbsp;
                                    <a href="/canmou/user/index">
                                        <button class="btn" type="button">返回</button>
                                    </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!--end-->
    <div class="footer">
        <div class="footer-inner">
            <div class="footer-content">
						<span class="bigger-120">
							Application &copy; 2013-2014
						</span>
            </div>
        </div>
    </div>
</div>
<include file="./Application/Canmou/View/after_body.phtml"/>
<script src="__PUBLIC__js/webuploader.js"></script>
<script src="__PUBLIC__js/upload.js"></script>
</body>
</html>