<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>管理员后台</title>
    <include file="./Application/Canmou/View/before_body.phtml"/>
</head>
<body class="no-skin">

<include file="./Application/Canmou/View/navbar.phtml"/>
<div class="main-container" id="main-container">
    <include file="./Application/Canmou/View/sidebar.phtml"/>
    <!--begin-->
    <div class="main-content">
        <div class="page-content">
            <div class="page-content-area">
                <div class="page-header">
                    <b><h1>
                            <if condition="$usertype eq 'add'">
                                添加管理员
                                <else/>
                                编辑管理员用户
                            </if>
                    </h1></b>
                </div>
                <include file="./Application/Canmou/View/tip.phtml"/>
                <div class="row">
                    <div class="col-xs-12">
                        <form class="form-horizontal" role="form" method="POST">
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-right" for="form-field-1">用户名</label>
                                <div class="col-sm-6">
                                    <input type="text" id="form-field-1" class="col-xs-10 col-sm-6" name="username" value=""/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-left" for="form-field-1">密码
                                </label>
                                <div class="col-sm-6">
                                    <input type="password" id="form-field-1" class="col-xs-10 col-sm-6" name="password" value=""/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label no-padding-left" for="form-field-1">确认密码
                                </label>
                                <div class="col-sm-6">
                                    <input type="password" id="form-field-1" class="col-xs-10 col-sm-6" name="repassword" value=""/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 no-padding-right control-label">状态</label>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="status" class="ace" checked="checked" value="1"/>
                                        <span class="lbl">启用</span>
                                    </label>
                                    <label>
                                        <input type="radio" name="status" class="ace" value="0"/>
                                        <span class="lbl">禁用</span>
                                    </label>
                                </div>
                            </div>
                            <div class="clearfix form-actions">
                                <div class="col-md-offset-3 col-md-9">
                                    <button class="btn btn-info" type="submit">提交</button> &nbsp; &nbsp; &nbsp;
                                    <a href="/canmou/user/index">
                                        <button class="btn" type="button">返回</button>
                                    </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!--end-->
    <div class="footer">
        <div class="footer-inner">
            <div class="footer-content">
						<span class="bigger-120">
							Application &copy; 2013-2014
						</span>
            </div>
        </div>
    </div>
</div>
<include file="./Application/Canmou/View/after_body.phtml"/>
</body>
</html>