<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>管理员后台</title>
    <include file="./Application/Canmou/View/before_body.phtml"/>
</head>
<body class="no-skin">

<include file="./Application/Canmou/View/navbar.phtml"/>
<div class="main-container" id="main-container">
    <include file="./Application/Canmou/View/sidebar.phtml"/>
    <!--begin-->
    <!--    {:hook('Tip')}-->
    <include file="./Application/Canmou/View/tip.phtml"/>
    <div class="main-content">
        <div class="page-content">
            <div class="page-content-area">
                <div class="row">
                    <div class="col-xs-12">
                        <h3 class="header smaller lighter blue">管理员列表</h3>
                        <div>
                            <div id="sample-table-2_wrapper" class="dataTables_wrapper form-inline no-footer">
                                <div class="row">
                                    <div class="col-xs-6">
                                    </div>
                                    <div class="col-xs-6">
                                    </div>
                                </div>
                                <table id="sample-table-2" class="table table-striped table-bordered table-hover dataTable no-footer">
                                    <thead>
                                    <tr role="row">
                                        <th width="60px" class="center sorting_disabled">
                                            <label class="position-relative">
                                                <input type="checkbox" class="ace">
                                                <span class="lbl"></span>
                                            </label>
                                        </th>
                                        <th>用户名</th>
                                        <th width="180px">注册时间</th>
                                        <th width="180px">最后登录时间</th>
                                        <th width="180px">最后登录ip</th>
                                        <th width="100px">状态</th>
                                        <th width="100px">操作</th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    <volist name="users" id="user">
                                        <tr role="row" class="even">
                                            <td class="center">
                                                <label class="position-relative">
                                                    <input type="checkbox" class="ace">
                                                    <span class="lbl"></span>
                                                </label>
                                            </td>
                                            <td>{$user['username']}</td>
                                            <td>{$user['created']|date="Y-m-d H:m:s",###}</td>
                                            <td>{$user['last_login_time']|date="Y-m-d H:m:s",###}</td>
                                            <td>{$user['last_login_ip']}</td>
                                            <td class="hidden-480 sorting_1">
                                                <if condition="$user['status'] eq 1">
                                                    <span class="label label-sm label-info">启用</span>
                                                    <else/>
                                                    <span class="label label-sm label-warning">禁用</span>
                                                </if>
                                            </td>
                                            <td>
                                                <div class="hidden-sm hidden-xs action-buttons">
                                                    <a class="green" href="{$user['id']}" >
                                                        <i class="ace-icon fa fa-pencil bigger-130"></i>
                                                    </a>
                                                    <a class="red" href="{$user['id']}" >
                                                        <i class="ace-icon fa fa-users bigger-130"></i>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    </volist>
                                    </tbody>
                                </table>
                                <div class="row">
                                    <div class="col-xs-6">
                                        <div class="dataTables_info" id="sample-table-2_info" role="status" aria-live="polite">
                                            共{$count}条记录
                                        </div>
                                    </div>
                                    <div class="col-xs-6">
                                        <div class="dataTables_paginate paging_simple_numbers" id="sample-table-2_paginate">
                                            <ul class="pagination">
                                                {$page}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--end-->
    <div class="footer">
        <div class="footer-inner">
            <div class="footer-content">
						<span class="bigger-120">
							Application &copy; 2013-2014
						</span>
            </div>
        </div>
    </div>
</div>
<include file="./Application/Canmou/View/after_body.phtml"/>
</body>
</html>
