<div class="content_v1 index_top_area">
    <div class="left" area="top_left" widget_type="area">
        <div id="_widget_211" name="gcategory_list_mao" widget_type="widget" class="widget">
            <div style="height:360px;"></div>
        </div>
    </div>
    <div class="right">
        <div id="module_middle" area="cycle_image" widget_type="area">
            <div id="_widget_698" name="cycle_image" widget_type="widget" class="widget">
                <div class="ad_cycle">
                    <div class="line"></div>
                    <div class="number">
                        <ul>
                            <foreach name="ads" item="ad" key="k">
                                <li class="<if condition="$k+1 eq 1">nonce<else/>initial</if>" target_src="{$ad.image_link}" target_link="{$ad.url_link}" alt="{$k+1}">
                                    {$k+1}
                                </li>
                            </foreach>
                        </ul>
                    </div>
                    <div class="number_bg"></div>
                    <a href="" class="listpic" target="_blank">
                        <img src="{$ads[0]['image_link']}" width="670" height="360" style="">
                    </a>
                </div>
            </div>
        </div>
        <div id="module_right" area="top_right" widget_type="area">
            <div id="_widget_166" name="image_ad" widget_type="widget" class="widget">
                <div class="base_top_right image_ad_area">
                    <a href="" target="_blank">
                        <img src="__PUBLIC__images/001.gif" width="250px" height="129px">
                    </a>
                </div>
            </div>
            <div id="_widget_907" name="register_and_apply" widget_type="widget" class="widget">
                <div class="base_top_right login_reg_area">
                    <a class="login" href="">
                        <div class="login_base_btn" id="mao_login" style="margin-left:12px;"
                             onmousemove="btLoginFocus()" onmouseout="focusOut()">登录
                        </div>
                    </a>
                    <a class="login" href="index.php?app=member&amp;act=register">
                        <div class="login_base_btn" id="mao_regist" style="margin-left:11px;"
                             onmousemove="btRegistFocus()" onmouseout="focusOut()">注册
                        </div>
                    </a>
                    <a class="login" href="index.php?app=apply" target="_blank">
                        <div class="login_base_btn" id="mao_join" style="margin-left:11px;" onmousemove="btJoinFocus()"
                             onmouseout="focusOut()">免费开店
                        </div>
                    </a>
                </div>

            </div>

            <div id="_widget_244" name="notice" widget_type="widget" class="widget">
                <div class="base_top_right last_news module_common_v1">
                    <div class="title_artical_type_v1">
                        <h3>最新动态</h3>
                        <a href="" target="_blank"
                           class="title_right">查看更多&gt;&gt;</a>

                        <div class="clear"></div>
                    </div>
                    <div class="module_common_content module_last_news">
                        <ul>

                            <li>
                                <a href="" target="_blank">庄主之家下单及配送流程调整公告
                                </a>
                            </li>
                            <li>
                                <a href="" target="_blank">庄主之家在线商城试运营！
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>
<script type="text/javascript">
    var tId;
    startScroll();
    $(function () {
        $('.ad_cycle li').each(function () {
            $(this).click(function () {
                slideHere($(this));
            }).mouseover(function () {
                console.log('mouseover');
                stopHere($(this));
            }).mouseout(function () {
                startScroll();
            });
        });
        $('.listpic').each(function () {
            $(this).mouseover(function () {
                stopScroll();
            }).mouseout(function () {
                startScroll();
            });
        });
    });
    function startScroll() {
        tId = setInterval(function () {
            var nextImg = $('.nonce').next('.initial');
            if (nextImg.length == 0) {
                nextImg = $($('.ad_cycle li')[0]);
            }
            slideHere($(nextImg));
        }, 1000);
    }
    function stopScroll() {
        clearInterval(tId);
    }
    function slideHere(imgObj) {
        $('.ad_cycle li').removeClass('nonce');
        $('.ad_cycle li').addClass('initial');
        imgObj.removeClass('initial');
        imgObj.addClass('nonce');
        if ($('.ad_cycle img').length) {
            $('.ad_cycle img')
                    .attr('src', imgObj.attr('target_src'))
                    .css('display', 'none')
                    .fadeIn('slow')
                    .parent().attr('href', imgObj.attr('target_link'))
                    .attr('target', '_blank');
        }
    }
    function stopHere(imgObj) {
        slideHere(imgObj);
        stopScroll();
    }
</script>
<script  type="text/javascript">
    function btLoginFocus(){
        $("#mao_login").css({"background":"#ff3400"});
    }
    function btRegistFocus(){
        $("#mao_regist").css({"background":"#ff3400"});
    }
    function btJoinFocus(){
        $("#mao_join").css({"background":"#ff3400"});
    }
    function focusOut(){
        $(".login_base_btn").css({"background":"#ff5600"});
    }
</script>