<div id="outfooter">
    <!--客服-->
    <!--
    <div class="bottomfix useropinion" id="useropinion" align="center" onmousemove="useropinionfocus()"
         onmouseout="useropinionunfocus()">
        <div id="opinion_point" align="center" style="display: none;">
            <a href="" target="_blank">
                在线<br>客服</a>
        </div>
    </div>-->
    <!--/客服-->
    <!--置顶-->
    <div class="bottomfix gotop" id="gotop" onmousemove="gotopfocus()" onmouseout="gotopunfocus()" onclick="gotop()"
         style="display: block;">
        <div id="toptext" style="display: none;">回顶部</div>
    </div>
    <!--/置顶-->
    <div id="footer">
        <div style="width:1150px;height:70px;background-color:#f5f5f5" align="center">
            <div style="width:980px;height:100%;position:relative;">

                <div class="tfoot_icon_list" align="center">
                    <ul>
                        <li class="icon01"></li>
                        <li class="icon02"></li>
                        <li class="icon03"></li>
                        <li class="icon04"></li>
                        <li class="icon05"></li>
                    </ul>
                </div>

            </div>

        </div>
        <div style="width:100%;height:2px;background-color:#e2e2e2;margin-top:15px;"></div>
        <div class="div_footer_out">
            <div class="div_footer_in">
                <dl>
                    <dt>食品安全</dt>
                    <dd><a href="" target="_blank">极品食材</a></dd>
                    <dd><a href="" target="_blank">产品朔源</a></dd>
                    <dd><a href="http://www.ubive.com/index.php?app=article&amp;act=view&amp;article_id=67"
                           target="_blank">生态自然</a></dd>
                    <dd><a href="" target="_blank">有机认证</a></dd>
                    <dd><a href="" target="_blank">绿色食品</a></dd>
                    <dd><a href="" target="_blank">食品检测</a></dd>
                    <dd><a href="" target="_blank">无公害产品</a></dd>
                </dl>
                <dl>
                    <dt>新手教程</dt>
                    <dd>
                        <a href="http://e.weibo.com/ubive?ref=http%3A%2F%2Fwww.ubive.com%2F" target="_blank">
                            购物流程
                        </a>
                    </dd>
                    <dd>
                        <a style="cursor:pointer">注册登录</a>
                    </dd>
                    <dd><a onclick="" title="" style="cursor:pointer">账户充值</a></dd>
                    <dd><a title="" style="cursor:pointer">如何提货</a></dd>
                    <dd><a  title="" style="cursor:pointer">会员政策</a></dd>
                    <dd><a title="" style="cursor:pointer">金融扶持</a></dd>
                    <dd><a title="" style="cursor:pointer">资金互助</a></dd>
                </dl>
                <dl>
                    <dt>配送方式</dt>
                    <dd><a href="http://www.ubive.com/index.php?app=article&amp;act=view&amp;article_id=19"
                           target="_blank">全程冷链</a></dd>
                    <dd><a href="http://www.ubive.com/index.php?app=article&amp;act=view&amp;article_id=20"
                           target="_blank">配送范围</a></dd>
                    <dd><a href="http://www.ubive.com/index.php?app=article&amp;act=view&amp;article_id=13"
                           target="_blank">运费标准</a></dd>
                    <dd><a href="http://www.ubive.com/index.php?app=article&amp;act=view&amp;article_id=13"
                           target="_blank">GPS定位跟踪</a></dd>
                </dl>
                <dl>
                    <dt>支付方式</dt>
                    <dd style="color:#574d55;font-size:12px;">货到付款</dd>
                    <dd style="color:#574d55;font-size:12px;">在线支付</dd>
                    <dd style="color:#574d55;font-size:12px;">账户余额支付</dd>
                </dl>
                <dl>
                    <dt>售后服务</dt>
                    <dd style="color:#574d55;font-size:12px;">退换货政策</dd>
                    <dd style="color:#574d55;font-size:12px;">退换货流程</dd>
                    <dd style="color:#574d55;font-size:12px;">退款</dd>
                    <dd style="color:#574d55;font-size:12px;">投诉建议</dd>
                    <dd style="color:#574d55;font-size:12px;">担保机制</dd>
                </dl>
                <dl>
                    <dt>帮助信息</dt>
                    <dd style="color:#574d55;font-size:12px;">安全食品采购指南</dd>
                    <dd style="color:#574d55;font-size:12px;">常见问题</dd>
                    <dd style="color:#574d55;font-size:12px;">电子优惠券的使用</dd>
                    <dd style="color:#574d55;font-size:12px;">礼品卡</dd>
                </dl>
            </div>
        </div>
        <div style="width:100%;height:2px;background-color:#e2e2e2"></div>
        <ul>
            <li>
                <a target="_blank" href="">关于我们</a>　|　 <a target="_blank" href="">联系我们</a>　|
                <a target="_blank" href="">服务条款</a>　|　 <a target="_blank" href="">友情链接</a>　|　
                <a target="_blank" href="">网站地图</a>　|　 <a target="_blank" href="">帮助中心</a>
            </li>
            <li>餐谋长版权所有</li>
        </ul>

        </div>
        <!--站长统计-->
        <!--/站长统计-->
    </div>
</div>