<div id="head">
    <h1 title="">
        <a href="">
            <img alt="" src="__PUBLIC__images/logo.png" height="100px" width="350px">
        </a>
    </h1>
    <div class="headercart">
        <div class="theadicon">
            <div class="theadicon_img03">
            </div>
            <div class="theadicon_img02">
            </div>
            <div class="theadicon_img01">
            </div>
        </div>
    </div>
    <div style="width:10px;height:20px;float:right;"></div>
    <div class="mainsearch" id="mainsearch" align="center" style="background:#ff5600;padding-top:2px;">
        <div style="height:42px;width:456px;background:#ffffff;">
            <form method="GET" action="">
                <div class="searchtype">
                    <ul class="searchtypeul">
                        <p id="searchgood">搜商品</p>
                        <p id="searchshop" style="display: none;">搜店铺</p>
                    </ul>
                </div>
                <div class="searchinput">
                    <input type="text" name="keyword" id="keyword" value="" placeholder="土猪" class="textsearchinput">
                </div>
                <div class="searchbut" id="divsearchbt">
                    <input type="submit" name="Submit" value="" id="submit" style="">
                </div>
            </form>
        </div>
    </div>
</div>