<div class="content_v1" area="top_down" widget_type="area">
    <!--floor-->
    <volist name="products_list" id="pro" key="k">
        <if condition="$pro.pro_list neq null">
        <div id="" name="my_goods_module" widget_type="widget" class="widget">
            <div class="module_common_v1">
                <div class="title_artical_type_v1">
                    <a href="" target="_blank" style="float:left;">
                        <h3>{$k}F - {$pro.cate_name}</h3></a>
                    <span style="float:left;font-size:15px;height:100%;width:12px;display:block;"></span>
                </div>

                <div class="module_common_content module_goods">
                    <ul>
                        <volist name="pro.pro_list" id="p">
                            <li>
                                <div class="lioutdiv">
                                    <div class="ligooddiv" align="center">
                                        <div class="goodsimgdiv" style="">
                                            <a href="" target="_blank">
                                                <img style="margin-top:1px;" src="/Public/upload/pro_img/{$p.main_image}" width="140" height="140" alt="赣南脐橙">
                                            </a>
                                        </div>
                                        <div class="name" align="left">
                                            <a style="text-align:left;" href="" target="_blank">
                                                {$p.title}
                                            </a>
                                        </div>
                                        <div class="bottomgoodsinfo">
                                            <div class="leftinfo">
                                                <font color="#ff5600" size="3" style="font-weight:bold">¥{$p.sell_price}</font>
                                                <font class="unit">/{$p.pro_size}</font>
                                            </div>
                                            <div class="clear"></div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </volist>

                        <div class="clear"></div>
                    </ul>
                    <div class="clear"></div>
                </div>

            </div>
        </div>
        </if>
    </volist>
    <!--/floor-->
</div>