<div id="mainnavbar" align="center">
<div id="mainnavbarcontent">
<div class="leftmenuinfo">
    <ul class="subnav">
        <li class="line" id="select_list_category">
            <a class="z_index" id="z_index_category" href="index.php?app=category">全部商品分类
                <img class="tri" id="ico_down" width="9" height="5" src="Public/default/images/ico_down_white.png" style="display: none;"/>
            </a>
            <div class="float_list" id="float_list_category" style="display: block;">
                <div class="module_common_category">
                    <div id="AllSort">
                        <volist name="categories" id="cate">
                            <dl>
                            <dt id="EFF_dt_{$cate.name}">
                                <a href="1" target="_blank">{$cate.name}</a>

                            </dt>
                            <if condition="$cate.children neq null">
                                <dd class="noDis" id="EFF_dd_{$cate.name}">
                                    <volist name="cate.children" id="c">
                                        <span>
                                            <a href="" target="_blank">
                                                {$c.name}</a><br>
                                        </span>
                                    </volist>
                                </dd>
                            </if>
                            </dl>
                        </volist>
                    </div>
                </div>
            </div>
        </li>
        <li>
            <div class="hover">
                <a href="index.php">
                    <span>首页</span>
                </a>
            </div>
        </li>
        <li>
            <div class="link">
                <a href="">
                    <span>商城文化</span>
                </a>
            </div>
        </li>
        <li>
            <div class="link">
                <a href="">
                    <span>企业文化</span>
                </a>
            </div>
        </li>
        <li>
            <div class="link">
                <a href="">
                    <span>风雪商城</span>
                </a>
            </div>
        </li>
        <li>
            <div class="link">
                <a href="">
                    <span>行业资讯</span>
                </a>
            </div>
        </li>
    </ul>
</div>
</div>
</div>
<script src="__PUBLIC__js/headbottom.js" type="text/javascript"></script>