<include file="./Application/Home/View/header.phtml"/>
    <script src="__PUBLIC__js/jquery.js" type="text/javascript"></script>
    <script src="__PUBLIC__js/ubmall.js" type="text/javascript"></script>
    <script src="__PUBLIC__js/select.js" type="text/javascript"></script>
    <script src="__PUBLIC__js/footer.js" type="text/javascript"></script>
    <script src="__PUBLIC__js/headtop.js" type="text/javascript"></script>

    <link href="__PUBLIC__css/shop.css" type="text/css" rel="stylesheet">
    <link href="__PUBLIC__css/footer.css" type="text/css" rel="stylesheet">
    <link href="__PUBLIC__css/header.css" type="text/css" rel="stylesheet">
    <link href="__PUBLIC__css/base.css" type="text/css" rel="stylesheet">
    <link href="__PUBLIC__css/jqzoom.css" type="text/css" rel="stylesheet">

    <script src="__PUBLIC__js/jquery.jqzoom.js" type="text/javascript"></script>
</head>
<body>
<div style="width:100%;min-width:1150px;" align="center">
    <!--topbar-->
    <include file="./Application/Home/View/topbar.phtml"/>
    <!--/topbar-->
    <div style="position: relative; z-index: 100; width: 1150px;" align="left" ectype="jqzoom_relative">
        <div style="width:100%;height:45px;"></div>
        <!--head-->
        <include file="./Application/Home/View/head.phtml"/>
        <!--/head-->
        <!--path-->
        <!--/path-->
        <div id="nav" style="border:#000 0px solid;">
            <div class="banner" style="border:#000 0px solid">
                <a href="index.php?app=store&amp;id=54565">
                    <img src="data/files/store_54565/other/store_banner.jpg" style="border:#000 0px solid;" width="1150"
                         height="120">
                </a></div>
            <div class="nav_bg"></div>
        </div>
        <div class="content_blank_area10"></div>
        <div class="content_blank_area10"></div>

        <!--content-->

        <div id="content">
            <!--left shop info-->
            <include file="./Application/Home/View/shop_left.phtml"/>
            <!--/left shop info-->
            <!--right product info-->
            <include file="./Application/Home/View/pro_content.phtml"/>
            <!--/right product info-->
            <div class="clear"></div>
        </div>
        <!--/content-->
        <div class="clear"></div>
    </div>
    <div class="footer_margin" style="background-color:#fff;"></div>
    <div class="footer_margin" style="background-color:#fff;"></div>
    <!--footer-->
    <include file="./Application/Home/View/footer.phtml"/>
    <!--/footer-->
</div>
<script type="text/javascript" src="__PUBLIC__js/goodsinfo.js"
        charset="utf-8"></script>
<script type="text/javascript" src="__PUBLIC__js/mlselection.js"
        charset="utf-8"></script>
<script type="text/javascript">
    $(function () {
        $('.amount_reduce').click(function () {
            me = $(this);
            element = me.parent('li').find('input');
            var val = Number(element.val());
            if (val > 1) {
                val = val - 1;
            }
            element.val(val);
            element.keyup();
        });
        $('.amount_increase').click(function () {
            me = $(this);
            element = me.parent('li').find('input');
            var val = Number(element.val());
            if (val < 200) {
                val = val + 1;
            }
            element.val(val);
            element.keyup();
        });
        $('.visitorregionname').click(addressselectiondialog);
        $('.visitorregionname, #span_price_refer_tip').click(function (e) {
            e.stopPropagation();
        });
        $(document.body).click(function () {
            $('#price_refer_tips').hide();
        });
    });
    /* buy */
    function buy() {
        if (goodsspec.getSpec() == null) {
            alert(lang.select_specs);
            return;
        }
        var spec_id = goodsspec.getSpec().id;
        var quantity = $("#quantity").val();
        if (quantity == '') {
            alert(lang.input_quantity);
            return;
        }
        if (parseInt(quantity) < 1) {
            alert(lang.invalid_quantity);
            return;
        }
        add_to_cart(spec_id, quantity);
    }

    /*立即购买*/
    function buy_to_cart() {
        if (goodsspec.getSpec() == null) {
            alert(lang.select_specs);
            return;
        }
        var spec_id = goodsspec.getSpec().id;

        var quantity = $("#quantity").val();
        if (quantity == '') {
            alert(lang.input_quantity);
            return;
        }
        if (parseInt(quantity) < 1) {
            alert(lang.invalid_quantity);
            return;
        }
        buy_add_to_cart(spec_id, quantity);
    }
    function buy_add_to_cart(spec_id, quantity) {
        var url = SITE_URL + '/index.php?app=cart&act=add';
        $.getJSON(url, {'spec_id': spec_id, 'quantity': quantity}, function (data) {
            if (data.done) {
                window.location.href = SITE_URL + '/index.php?app=cart';
            }
            else {
                alert(data.msg);
            }
        });
    }

    /* add cart */
    function add_to_cart(spec_id, quantity) {
        var url = SITE_URL + '/index.php?app=cart&act=add';
        $.getJSON(url, {'spec_id': spec_id, 'quantity': quantity}, function (data) {
            if (data.done) {
                var b = $("#goodsDetailAddCartBtn");
                var c = $("<img>"), d = b.offset().top - 166, e = b.offset().left, f = $("#J_miniCart").offset().top + 20, g = $("#J_miniCart").offset().left + 60,
                    h = $("#goodsPicList").find("li").eq(0).find("img").attr("src");
                c.css({
                    display: "block",
                    width: "160px",
                    height: "160px",
                    position: "absolute",
                    top: d,
                    left: e,
                    "z-index": "1000",
                    border: "2px solid #f60"
                });
                c.attr("src", h);
                c.appendTo("body").animate({
                    top: f,
                    left: g,
                    width: "20px",
                    height: "20px"
                }, 400, "linear", function () {
                    c.remove();
                    var num = $(".J_cartNum").text();
                    var curQuantity = parseInt(num.substring(1, num.length - 1)) + parseInt(quantity);
                    $(".J_cartNum").text(num == null || num == '' ? "(" + parseInt(quantity) + ")" : "(" + curQuantity + ")");
                });
            }
            else {
                alert(data.msg);
            }
        });
    }
    function showAnim() {

    }
    var specs = new Array();
    specs.push(new spec(1975, '', '', 566.00, 977));
    var specQty = 0;
    var defSpec = 1975;
    var goodsspec = new goodsspec(specs, specQty, defSpec);
    //]]>
</script>
</body>
</html>