<!--商品详细页，进入店铺页面 左边的店铺信息-->
<div id="left">
    <div class="user">
        <div class="user_photo" style="border:#f00 0px solid">
            <h2>店铺名称</h2>
            <div class="photo">
                <a href="">
                    <img src="/Public/upload/shop_img/{$shop.image}" width="100" height="100">
                </a>
            </div>
        </div>
        <div class="user_data" style="border:#000 0px solid;margin-top:20px;margin-left:11px;">
            <table class="table table-bordered" style="table-layout:fixed">
                <tbody>
                <tr>
                    <td width="60">店主</td>
                    <td>
                        <div style="word-break:break-all;">{$shop.name}</div>
                    </td>
                </tr>
                <tr>
                    <td>创店时间</td>
                    <td>{$shop.name|date="Y-m-d H:m:s",###}</td>
                </tr>
                <tr>
                    <td>联系电话</td>
                    <td>{$shop.telephone}</td>
                </tr>
                <tr>
                    <td>客服QQ</td>
                    <td>{$shop.qq}</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="index_btn" align="center" style="border:#F00 0px solid;height:30px;width:184px;margin-left:11px;margin-bottom:14px;">
            <a class="join_in" style="float:left;width:85px;height:34px;text-align:center;line-height:34px;background:#ccc;"
               href="javascript:collect_store(54565)">
                <div class="mao_btn" id="store_farm" style="color:#000;" onmousemove="btStoreFocus();"
                     onmouseout="focusOut()">收藏店铺
                </div>
            </a>
            <a class="join_in" style="float:right;background:#ccc;width:85px;height:34px;text-align:center;line-height:34px;"
               target="_blank" href="index.php?app=message&amp;act=send&amp;to_id=54565">
                <div class="mao_btn" id="send_msg" style="color:#000;">进入店铺
                </div>
            </a>
        </div>
            <div class="clear"></div>
    </div>
</div>