<!--top 顶部固定-->
<div id="topbar" align="center">
    <div id="topbarcontent">
        <div class="leftmenuinfo">
            您好,&nbsp;<a href="">游客</a>&nbsp;,欢迎光临餐谋长商城
            [<a href="">登录</a>]
            [<a href="">免费注册</a>]
        </div>
        <div class="rightmenuinfo" align="right">
            <ul class="subnav">
                <li class="line"><a href="index.php?app=article&amp;code=help">帮助中心</a></li>
                <li class="line"><a href="index.php?app=message&amp;act=newpm">站内消息</a></li>
                <li class="topbar_select_list select_list" id="select_list">
                    <a class="z_index" href="index.php?app=member">我的餐谋长</a>
                    <ul class="float_list" id="float_list" style="display: none;">
                        <li><a href="index.php?app=buyer_order">我的订单</a></li>
                        <li><a href="index.php?app=my_favorite">我的收藏</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>